---
framework: mocha
preRun:
     command:
        - npm install
        - npm run prepare
preMerge:
  pattern:
    - "./test/**/*.js"
postMerge:
  pattern: 
    - "./test/**/*.js"
postRun:
     command:
        - node --version
configFile: .mocharc.yml
version: 1.0.0